block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "CI (stable, aarch64-unknown-linux-gnu)",
    "CI (stable, arm-unknown-linux-gnueabi)",
    "CI (stable, armv7-unknown-linux-gnueabihf)",
    "CI (stable, i686-unknown-linux-gnu)",
    "CI (stable, i686-unknown-linux-musl)",
    "CI (stable, mips-unknown-linux-gnu)",
    "CI (stable, mips64-unknown-linux-gnuabi64)",
    "CI (stable, mips64el-unknown-linux-gnuabi64)",
    "CI (stable, mipsel-unknown-linux-gnu)",
    "CI (stable, powerpc-unknown-linux-gnu)",
    "CI (stable, powerpc64le-unknown-linux-gnu)",
    "CI (stable, s390x-unknown-linux-gnu)",
    "CI (stable, x86_64-unknown-linux-gnu)",
    "CI (stable, x86_64-unknown-linux-musl)",
    "CI (stable, x86_64-apple-darwin)",

    "CI (stable, --features=async-tokio, x86_64-unknown-linux-gnu)",
    "CI (stable, --features=mio-evented, x86_64-unknown-linux-gnu)",

    "CI (1.46.0, --features=async-tokio, x86_64-unknown-linux-gnu)",
    "CI (1.46.0, --features=mio-evented, x86_64-unknown-linux-gnu)",
    "CI (1.46.0, x86_64-unknown-linux-gnu)",
    "CI (1.46.0, x86_64-apple-darwin)",

    "checks"
]
timeout_sec = 3600
